language: python
python:
  - 3
  - 3.1
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - 3.8
install:
  - pip install pipenv
  - pipenv install
  - python setup.py install
  - pip install pytest pytest-cov
  - pip install codecov
script:
  - pytest --cov
after_success:
  - codecov